recipe_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view
from recipes.views import records, RecipeListView, about

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('search/', records, name='search'),
    path('about/', records, name='about'),
    path('list/', RecipeListView.as_view(), name='list'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from .views import home, RecipeListView, RecipeDetailView, logout_view, about, add_recipe_view

app_name = 'recipes'

urlpatterns = [
    path('', home, name='home'),
    path('list/', RecipeListView.as_view(), name='list'),
    path('list/<int:pk>/', RecipeDetailView.as_view(), name='details'),
    path('logout/', logout_view, name='logout'),
    path('about/', about, name='about'),
    path('add/', add_recipe_view, name='add_recipe'),  
]

recipes/models.py
from django.db import models
from django.shortcuts import reverse

class Recipe(models.Model):
    name = models.CharField(max_length=120)
    cooking_time = models.FloatField(help_text='In minutes')
    ingredients = models.CharField(max_length=350)
    description = models.TextField()
    pic = models.ImageField(upload_to='recipes', default='no_image.jpg')

    @property
    def difficulty(self):
        ingredients = self.ingredients.split(', ')
        cooking_time_minutes = float(self.cooking_time)
        if cooking_time_minutes < 20 and len(ingredients) < 6:
            return 'Easy'
        elif cooking_time_minutes < 20 and len(ingredients) >= 6:
            return 'Medium'
        elif cooking_time_minutes >= 20 and len(ingredients) < 6:
            return 'Intermediate'
        elif cooking_time_minutes >= 20 and len(ingredients) >= 6:
            return 'Hard'

    def get_absolute_url(self):
        return reverse('recipes:details', kwargs={'pk': self.pk})

    def __str__(self):
        return str(self.name)

recipes/forms.py
from django import forms
from .models import Recipe

# Choices for chart type and difficulty level
CHART_CHOICES = (
    ('#1', 'Bar Chart'),
    ('#2', 'Pie Chart'),
    ('#3', 'Line Chart'),
)

DIFFICULTY_CHOICES = (
    ('#1', 'Easy'),
    ('#2', 'Medium'),
    ('#3', 'Intermediate'),
    ('#4', 'Hard'),
)


class RecipesSearchForm(forms.Form):
    recipe_diff = forms.ChoiceField(choices=DIFFICULTY_CHOICES)
    chart_type = forms.ChoiceField(choices=CHART_CHOICES)


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['name', 'cooking_time', 'ingredients', 'description', 'pic']

recipe_project/views.py
from django.shortcuts import render, redirect  
#Django authentication libraries           
from django.contrib.auth import authenticate, login, logout
#Django Form for authentication
from django.contrib.auth.forms import AuthenticationForm    
#define a function view called login_view that takes a request from user
def login_view(request):                              
   error_message = None   
   #form object with username and password fields                             
   form = AuthenticationForm()                            
   #when user hits "login" button, then POST request is generated
   if request.method == 'POST':       
       #read the data sent by the form via POST request                   
       form =AuthenticationForm(data=request.POST)
       #check if form is valid
       if form.is_valid():                                
           username=form.cleaned_data.get('username')      #read username
           password = form.cleaned_data.get('password')    #read password
           #use Django authenticate function to validate the user
           user=authenticate(username=username, password=password)
           if user is not None:                    #if user is authenticated
          #then use pre-defined Django function to login
               login(request, user)                
               return redirect('/list') #& send the user to desired page
       else:                                               #in case of error
           error_message ='ooops.. something went wrong'   #print error message
   #prepare data to send from view to template
   context ={                                             
       'form': form,                                 #send the form data
       'error_message': error_message                     #and the error_message
   }
   #load the login page using "context" information
   return render(request, 'auth/login.html', context)     
#define a function view called logout_view that takes a request from user
def logout_view(request):                                  
   logout(request)          #the use pre-defined Django function to logout
   return redirect('login') #after logging out go to login form (or whichever page you want)

recipes/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from .models import Recipe
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .forms import RecipesSearchForm
import pandas as pd
from .utils import get_chart
from django.db.models import Count, Case, Value, When, CharField
from .forms import RecipesSearchForm, RecipeForm 

def home(request):
    return render(request, 'recipes/recipes_home.html')

class RecipeListView(LoginRequiredMixin, ListView):
    model = Recipe
    template_name = 'recipes/main.html'

class RecipeDetailView(LoginRequiredMixin, DetailView):
    model = Recipe
    template_name = 'recipes/details.html'

@login_required
def records(request):
    form = RecipesSearchForm(request.POST or None)
    recipe_df = None
    chart = None
    qs = None
    
    if request.method == 'POST' and form.is_valid():
        recipe_diff = form.cleaned_data['recipe_diff']
        chart_type = form.cleaned_data['chart_type']
        
        difficulty_map = {
            '#1': 'Easy',
            '#2': 'Medium',
            '#3': 'Intermediate',
            '#4': 'Hard'
        }
        recipe_diff = difficulty_map.get(recipe_diff)

        if recipe_diff:
            qs = Recipe.objects.annotate(
                ingredient_count=Count('ingredients'),
                calculated_difficulty=Case(
                    When(cooking_time__lt=20, ingredient_count__lt=6, then=Value('Easy')),
                    When(cooking_time__lt=20, ingredient_count__gte=6, then=Value('Medium')),
                    When(cooking_time__gte=20, ingredient_count__lt=6, then=Value('Intermediate')),
                    When(cooking_time__gte=20, ingredient_count__gte=6, then=Value('Hard')),
                    default=Value('Unknown'),
                    output_field=CharField()
                )
            ).filter(calculated_difficulty=recipe_diff)

            if qs.exists():
                
                data = []
                for recipe in qs:
                    data.append({
                        'name': recipe.name,  
                        'cooking_time': recipe.cooking_time,
                        'difficulty': recipe.calculated_difficulty  
                    })
                recipe_df = pd.DataFrame(data)
                chart = get_chart(chart_type, recipe_df, labels=recipe_df['name'].values)
                recipe_df = recipe_df.to_html(escape=False)

    context = {
        'form': form,
        'recipes': qs,  
        'chart': chart,
    }
    return render(request, 'recipes/search.html', context)



def logout_view(request):
    logout(request)
    return redirect('recipes:home')

def about(request):
    return render(request, 'recipes/about.html')

@login_required
def add_recipe_view(request):
    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('recipes:list')  
    else:
        form = RecipeForm()

    return render(request, 'recipes/add_recipe.html', {'form': form})

recipes/templates/recipes/about.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>RecipeApp | About</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/styles.css' %}" />

</head>

<body>
    <nav>
        <ul>
            <li>
                <a href="{% url 'recipes:home' %}" title="Home">
                    <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px"
                        fill="#f76c01">
                        <path
                            d="M240-200h120v-240h240v240h120v-360L480-740 240-560v360Zm-80 80v-480l320-240 320 240v480H520v-240h-80v240H160Zm320-350Z" />
                    </svg>

                </a>
            </li>
            <li>
                <a href="{% url 'recipes:list' %}" title="Recipes">Recipes</a>
            </li>
            <li><a href="{% url 'search' %}">Search</a></li>
            <li>
                <a href="{% url 'recipes:add_recipe' %}" title="Add Recipe">Add Recipe</a>
            </li>
            <li>
                <a href="{% url 'recipes:about' %}" title="About">About</a>
            </li>
            <li>
                <a href="{% url 'recipes:logout' %}" title="Logout">
                    <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px"
                        fill="#f76c01">
                        <path
                            d="M200-120q-33 0-56.5-23.5T120-200v-160h80v160h560v-560H200v160h-80v-160q0-33 23.5-56.5T200-840h560q33 0 56.5 23.5T840-760v560q0 33-23.5 56.5T760-120H200Zm220-160-56-58 102-102H120v-80h346L364-622l56-58 200 200-200 200Z" />
                    </svg>

                </a>
            </li>
        </ul>
    </nav>
    <div class="about-container">
        <h3>Connect with me on:</h3>
        <ul>
            <li><a href="https://www.linkedin.com/in/julia-atamas/" target="_blank">LinkedIn</a></li>
            <li><a href="https://github.com/aeueoe" target="_blank">GitHub</a></li>
            <li><a href="https://atamas-portfolio.vercel.app/" target="_blank">Portfolio</a></li>
        </ul>
    </div>
</body>

</html>

recipes/templates/recipes/add_recipe.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>RecipeApp | Add recipe</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/styles.css' %}" />

    <style type="text/css">
        body {
            background: url("{% static 'recipes/images/bg2.jpg' %}") no-repeat fixed;
            background-size: cover;

        }
    </style>
</head>

<body>
    <nav>
        <ul>
            <li>
                <a href="{% url 'recipes:home' %}" title="Home">
                    <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px"
                        fill="#f76c01">
                        <path
                            d="M240-200h120v-240h240v240h120v-360L480-740 240-560v360Zm-80 80v-480l320-240 320 240v480H520v-240h-80v240H160Zm320-350Z" />
                    </svg>

                </a>
            </li>
            <li>
                <a href="{% url 'recipes:list' %}" title="Recipes">Recipes</a>
            </li>
            <li><a href="{% url 'search' %}">Search</a></li>
            <li>
                <a href="{% url 'recipes:add_recipe' %}" title="Add Recipe">Add Recipe</a>
            </li>
            <li>
                <a href="{% url 'recipes:about' %}" title="About">About</a>
            </li>
            <li>
                <a href="{% url 'recipes:logout' %}" title="Logout">
                    <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px"
                        fill="#f76c01">
                        <path
                            d="M200-120q-33 0-56.5-23.5T120-200v-160h80v160h560v-560H200v160h-80v-160q0-33 23.5-56.5T200-840h560q33 0 56.5 23.5T840-760v560q0 33-23.5 56.5T760-120H200Zm220-160-56-58 102-102H120v-80h346L364-622l56-58 200 200-200 200Z" />
                    </svg>

                </a>
            </li>
        </ul>
    </nav>
    <h1>Add Recipe</h1>

    {% if messages %}
    {% for message in messages %}
    <script>alert("{{ message }}");</script>
    {% endfor %}
    {% endif %}

    <div class="add-form">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn" type="submit">Add Recipe</button>
        </form>
    </div>
</body>

</html>

recipes/templates/recipes/details.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>RecipeApp | Details</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/styles.css' %}" />

    <style type="text/css">
        body {
            background: url("{% static 'recipes/images/bg2.jpg' %}") no-repeat fixed;
            background-size: cover;

        }
    </style>
</head>

<body>
    <nav>
        <ul>
            <li>
                <a href="{% url 'recipes:home' %}" title="Home">
                    <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px"
                        fill="#f76c01">
                        <path
                            d="M240-200h120v-240h240v240h120v-360L480-740 240-560v360Zm-80 80v-480l320-240 320 240v480H520v-240h-80v240H160Zm320-350Z" />
                    </svg>

                </a>
            </li>
            <li>
                <a href="{% url 'recipes:list' %}" title="Recipes">Recipes</a>
            </li>
            <li><a href="{% url 'search' %}">Search</a></li>
            <li>
                <a href="{% url 'recipes:add_recipe' %}" title="Add Recipe">Add Recipe</a>
            </li>
            <li>
                <a href="{% url 'recipes:about' %}" title="About">About</a>
            </li>
            <li>
                <a href="{% url 'recipes:logout' %}" title="Logout">
                    <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px"
                        fill="#f76c01">
                        <path
                            d="M200-120q-33 0-56.5-23.5T120-200v-160h80v160h560v-560H200v160h-80v-160q0-33 23.5-56.5T200-840h560q33 0 56.5 23.5T840-760v560q0 33-23.5 56.5T760-120H200Zm220-160-56-58 102-102H120v-80h346L364-622l56-58 200 200-200 200Z" />
                    </svg>

                </a>
            </li>
        </ul>
    </nav>
    <div class="wrapper">
        <div class="recipe-image">
            <img src="{{ MEDIA_URL }}{{ object.pic.url }}" alt="{{ object.name }}" />
        </div>
        <div class="recipe-details">
            <h2>{{ object.name }}</h2>
            <div class="recipe-info">
                <b>Cooking Time (min): </b> {{ object.cooking_time|floatformat:0 }} <br />
                <b>Difficulty: </b> {{ object.difficulty }} <br />
            </div>
            <div class="recipe-description">
                <b>Ingredients: </b> {{ object.ingredients }} <br />
                <b>Description: </b> {{ object.description }} <br />
            </div>
        </div>
    </div>
</body>

</html>

recipes/templates/recipes/main.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>RecipeApp | Recipes</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/styles.css' %}" />

    <style type="text/css">
        body {
            background: url("{% static 'recipes/images/bg2.jpg' %}") no-repeat fixed;
            background-size: cover;

        }
    </style>
</head>

<body>
    <nav>
        <ul>
            <li>
                <a href="{% url 'recipes:home' %}" title="Home">
                    <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px"
                        fill="#f76c01">
                        <path
                            d="M240-200h120v-240h240v240h120v-360L480-740 240-560v360Zm-80 80v-480l320-240 320 240v480H520v-240h-80v240H160Zm320-350Z" />
                    </svg>

                </a>
            </li>
            <li>
                <a href="{% url 'recipes:list' %}" title="Recipes">Recipes</a>
            </li>
            <li><a href="{% url 'search' %}">Search</a></li>
            <li>
                <a href="{% url 'recipes:add_recipe' %}" title="Add Recipe">Add Recipe</a>
            </li>
            <li>
                <a href="{% url 'recipes:about' %}" title="About">About</a>
            </li>
            <li>
                <a href="{% url 'recipes:logout' %}" title="Logout">
                    <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px"
                        fill="#f76c01">
                        <path
                            d="M200-120q-33 0-56.5-23.5T120-200v-160h80v160h560v-560H200v160h-80v-160q0-33 23.5-56.5T200-840h560q33 0 56.5 23.5T840-760v560q0 33-23.5 56.5T760-120H200Zm220-160-56-58 102-102H120v-80h346L364-622l56-58 200 200-200 200Z" />
                    </svg>

                </a>
            </li>
        </ul>
    </nav>
    <div class="grid-container">
        {% for object in object_list %}
        <div class="grid-item">
            <div class="image-container">
                <img src="{{ object.pic.url }}" alt="{{ object.name }}" />
            </div>
            <div class="recipe-info">
                <h4><a href="{{ object.get_absolute_url }}">{{ object.name }}</a></h4>
                <div>
                    <b>Cooking Time (min): </b> {{ object.cooking_time|floatformat:0 }} <br />
                    <b>Difficulty: </b> {{ object.difficulty }} <br />
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</body>

</html>

recipes/templates/recipes/recipes_home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>RecipeApp | Home</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/styles.css' %}" />

    <style type="text/css">
        body {
            background: url("{% static 'recipes/images/bg.jpg' %}") no-repeat fixed;
            background-size: cover;

        }
    </style>
</head>

<body>
    <div class="container">
        <div class="hero">
            <h1>Welcome to RecipeApp</h1>
            <h2>Discover new recipes and cooking inspiration</h2>
            <a href="{% url 'login' %}" class="btn btn-primary">Login</a>
        </div>
    </div>
</body>

</html>

recipes/templates/recipes/search.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>RecipeApp | Search</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/styles.css' %}" />

    <style type="text/css">
        body {
            background: url("{% static 'recipes/images/bg2.jpg' %}") no-repeat fixed;
            background-size: cover;

        }
    </style>
</head>

<body>
    <nav>
        <ul>
            <li>
                <a href="{% url 'recipes:home' %}" title="Home">
                    <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px"
                        fill="#f76c01">
                        <path
                            d="M240-200h120v-240h240v240h120v-360L480-740 240-560v360Zm-80 80v-480l320-240 320 240v480H520v-240h-80v240H160Zm320-350Z" />
                    </svg>

                </a>
            </li>
            <li>
                <a href="{% url 'recipes:list' %}" title="Recipes">Recipes</a>
            </li>
            <li><a href="{% url 'search' %}">Search</a></li>
            <li>
                <a href="{% url 'recipes:add_recipe' %}" title="Add Recipe">Add Recipe</a>
            </li>
            <li>
                <a href="{% url 'recipes:about' %}" title="About">About</a>
            </li>
            <li>
                <a href="{% url 'recipes:logout' %}" title="Logout">
                    <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px"
                        fill="#f76c01">
                        <path
                            d="M200-120q-33 0-56.5-23.5T120-200v-160h80v160h560v-560H200v160h-80v-160q0-33 23.5-56.5T200-840h560q33 0 56.5 23.5T840-760v560q0 33-23.5 56.5T760-120H200Zm220-160-56-58 102-102H120v-80h346L364-622l56-58 200 200-200 200Z" />
                    </svg>

                </a>
            </li>
        </ul>
    </nav>
    <h1>Search for Recipes</h1>
    <div class="search-container">
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-action" type="submit">Search</button>
        </form>
        {% if recipes %}
        <h3>Search Results</h3>
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Cooking Time</th>
                    <th>Difficulty</th>
                </tr>
            </thead>
            <tbody>
                {% for recipe in recipes %}
                <tr>
                    <td><a href="{{ recipe.get_absolute_url }}">{{ recipe.name }}</a></td>
                    <td>{{ recipe.cooking_time }}</td>
                    <td>{{ recipe.calculated_difficulty }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <img alt="chart" src="data:image/png;base64,{{ chart|safe }}" />
        {% else %}
        <h3>No Data Available</h3>
        {% endif %}
    </div>
</body>

</html>